FROM python:3

RUN git clone https://github.com/manolo2829/manudiiez-examen-final-2023.git

WORKDIR /manudiiez-examen-final-2023

RUN pip install -r requirements.txt

CMD ["python3", "-m", "unittest"]